const panel=document.getElementById('conversa');
const original=panel.innerHTML;
const examples={gastos:original,lembrete:'<span class="chat-date">EXEMPLO DE CONVERSA</span><p class="bubble sent">Me lembre da troca de óleo sexta, às 9h.<small>09:14</small></p><p class="bubble received">Sexta-feira, 2 de outubro, às 9h: troca de óleo do seu caminhão. Confirma?<small>09:14</small></p><p class="bubble sent">Confirmo.<small>09:15</small></p><p class="bubble received">Lembrete agendado para 02/10 às 9h.<small>09:15 · Simulação</small></p><span class="chat-date">NO DIA E HORÁRIO COMBINADOS</span><p class="bubble received">Seu lembrete: troca de óleo do caminhão hoje, às 9h.<small>09:00 · Simulação de entrega</small></p>',documento:'<span class="chat-date">EXEMPLO DE CONVERSA</span><p class="bubble sent">Enviei o PDF do frete. Me ajuda a entender?<small>09:14</small></p><p class="bubble received">Claro. Neste exemplo, encontrei:<br><br><strong>Origem:</strong> Curitiba, PR<br><strong>Destino:</strong> Joinville, SC<br><strong>Valor informado:</strong> R$ 1.800,00<small>09:14</small></p><p class="bubble received">Quer analisar os custos dessa viagem? Me conte o consumo do caminhão e o preço do diesel.<small>09:15</small></p><p class="bubble sent">Quero sim.<small>09:15</small></p>'};
examples.audio='<span class="chat-date">EXEMPLO DE CONVERSA · ÁUDIO TRANSCRITO</span><p class="bubble sent">“Abasteci 200 litros e paguei R$ 1.200 hoje.”<small>Áudio ilustrativo · 09:14</small></p><p class="bubble received">Entendi: 200 litros por R$ 1.200,00. O litro saiu por R$ 6,00.<br><br>Qual era a quilometragem do caminhão?<small>09:14</small></p><p class="bubble sent">185 mil quilômetros.<small>09:15</small></p><p class="bubble received">Abastecimento de hoje: 200 litros, R$ 1.200,00 e 185.000 km. Posso registrar?<small>09:15 · Simulação</small></p>';
examples.frete='<span class="chat-date">EXEMPLO FICTÍCIO · LEITURA DE PRINT</span><p class="bubble sent">Recebi um print dessa oferta. Esse frete compensa?<small>09:14 · Imagem não exibida nesta simulação</small></p><p class="bubble received">No exemplo, a oferta informa R$ 2.500 por 400 km. Qual o consumo do caminhão, o preço do diesel e os outros custos? Vai ter retorno vazio?<small>09:14</small></p><p class="bubble sent">2,5 km/l, diesel a R$ 6, pedágio R$ 180 e mais R$ 360 de custos. Considere só a ida por enquanto.<small>09:15</small></p><div class="bubble received"><strong>Vamos às contas da ida:</strong><dl><div><dt>Frete</dt><dd>R$ 2.500,00</dd></div><div><dt>Diesel · 160 litros</dt><dd>R$ 960,00</dd></div><div><dt>Pedágio + outros custos</dt><dd>R$ 540,00</dd></div><div class="total"><dt>Sobra estimada</dt><dd>R$ 1.000,00</dd></div></dl><p>A ida tem saldo positivo com esses dados. Antes de aceitar, precisamos incluir retorno, tempo parado e qualquer custo que ficou de fora. Essa sobra ainda não é lucro líquido.</p><small>09:15 · Valores ilustrativos</small></div>';
const tabs=[...document.querySelectorAll('[data-example]')];
function select(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1});panel.innerHTML=examples[tab.dataset.example];panel.setAttribute('aria-labelledby',tab.id)}
document.querySelectorAll('[data-open-example]').forEach(link=>link.addEventListener('click',()=>select(tabs.find(tab=>tab.dataset.example===link.dataset.openExample))));
select(tabs.find(tab=>tab.dataset.example==='frete'));
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>select(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();select(tabs[next]);tabs[next].focus()}})});
